// Prepares what the module needs to know about itself and the TouchPoint script it keeps installed.
//
// The module and the script are one thing with one version, the `version` in package.json: they are released together,
// so a new version of one is a new version of the other. (That version is stamped in from the release's git tag by
// set-version.mjs; see there.) This:
//
// - writes that version into touchpoint/CompanionMeetings.py, as its VERSION, so the script always says which release
//   it is part of, and
// - writes src/scriptSource.ts: a copy of the script, so the module carries it whether it runs from dist/ in
//   development or from a packaged build, plus the version and repository address that the link to the matching
//   script is made from.
//
// Run by `npm run build`; run `npm run embed` after editing the script. Tests fail if the files this writes and their
// sources disagree.
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

export const SCRIPT_PATH = 'touchpoint/CompanionMeetings.py'

/** Does the work, in the project at `rootDirectory` (the repository, unless testing). */
export function embed(rootDirectory) {
	const file = (relativePath) => path.join(rootDirectory, relativePath)
	const read = (relativePath) => readFileSync(file(relativePath), 'utf8').replace(/\r\n/g, '\n')

	const packageJson = JSON.parse(read('package.json'))
	const version = String(packageJson.version)
	if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$/.test(version)) {
		throw new Error(`package.json's version, "${version}", is not a version like 1.2.3 or 1.2.3-beta.1`)
	}

	const repositoryUrl = String(packageJson.repository?.url ?? '')
		.replace(/^git\+/, '')
		.replace(/\.git$/, '')
	if (!/^https:\/\/github\.com\/[^/]+\/[^/]+$/.test(repositoryUrl)) {
		throw new Error(`package.json repository.url is not a GitHub repository address: ${repositoryUrl}`)
	}

	const versionLine = /^VERSION = "[^"]*"$/m
	let source = read(SCRIPT_PATH)
	if (!versionLine.test(source)) throw new Error(`${SCRIPT_PATH} has no VERSION line`)
	source = source.replace(versionLine, `VERSION = "${version}"`)
	writeFileSync(file(SCRIPT_PATH), source)

	writeFileSync(
		file('src/scriptSource.ts'),
		`// Generated by scripts/embed-script.mjs. Do not edit; run \`npm run embed\`.

/** Where the script is, in the repository. */
export const SCRIPT_PATH = ${JSON.stringify(SCRIPT_PATH)}

/**
 * The version of this module, which is also the version of the script it carries and installs in TouchPoint.
 * A release with this version, tagged v + the version, has the matching script attached to it.
 */
export const MODULE_VERSION = ${JSON.stringify(version)}

/** The GitHub repository this module is published from. */
export const REPOSITORY_URL = ${JSON.stringify(repositoryUrl)}

export const SCRIPT_SOURCE = ${JSON.stringify(source)}
`,
	)

	return { version, scriptPath: SCRIPT_PATH }
}

/** The project to work in: `--root <directory>` if given (for testing), otherwise this repository. */
export function projectRoot(argv) {
	const flag = argv.indexOf('--root')
	return flag >= 0 ? path.resolve(argv[flag + 1]) : fileURLToPath(new URL('../', import.meta.url))
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
	const { version } = embed(projectRoot(process.argv))
	console.log(`Embedded ${SCRIPT_PATH}, as version ${version}`)
}
