// Copies touchpoint/CompanionMeetings.py into src/scriptSource.ts, so the module carries the script it keeps
// installed in TouchPoint, whether it's run from dist/ in development or from a packaged build.
//
// Run by `npm run build`; run `npm run embed` after editing the script.  A test fails if the two disagree.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = new URL('../', import.meta.url)
const source = readFileSync(new URL('touchpoint/CompanionMeetings.py', root), 'utf8').replace(/\r\n/g, '\n')

const version = /^VERSION = "([0-9.]+)"/m.exec(source)?.[1]
if (!version) throw new Error('touchpoint/CompanionMeetings.py has no VERSION')

const out = `// Generated by scripts/embed-script.mjs from touchpoint/CompanionMeetings.py. Do not edit; run \`npm run embed\`.

export const SCRIPT_VERSION = ${JSON.stringify(version)}

export const SCRIPT_SOURCE = ${JSON.stringify(source)}
`

writeFileSync(fileURLToPath(new URL('src/scriptSource.ts', root)), out)
console.log(`Embedded CompanionMeetings.py version ${version}`)
